spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://0.0.0.0:5432/postgres
    username: postgres
    password: 123456
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
#      ddl-auto: create
    ddl-auto: update # 每次运行程序更新数据
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect


